server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: 220808

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 925624317651-ich8phd8o9o7pivkab32cru4lnbg44eq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 500569335262873
            client-secret: 0b97dc3e5f3682a2445e1aabf986823c
            scope:
              - email
              - public_profile   #페이스북에서 그렇게 한거
          naver:
            client-id: si_QQxIIg7SbSlND2eG7
            client-secret: 8MQqA3C4F0
            scope:
              - email
              - profile   #페이스북에서 그렇게 한거
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌

